steps:
    - name: 'node'
      entrypoint: 'npm'
      args: ['install']

    - name: 'node'
      entrypoint: 'npm'
      args: ['run', 'build']

    - name: "gcr.io/cloud-builders/gcloud"
      args:
          - "functions"
          - "deploy"
          - "daily-tasks"
          - "--trigger-topic"
          - "daily-tasks"
          - "--entry-point"
          - "dailyTasks"
          - "--region"
          - "europe-west1"
          - "--runtime"
          - "nodejs20"
          - "--memory"
          - "256MB"
          - "--timeout"
          - "540s"
          - "--source"
          - "."

    - name: "gcr.io/cloud-builders/gcloud"
      args:
          - "functions"
          - "deploy"
          - "monthly-tasks"
          - "--trigger-topic"
          - "monthly-tasks"
          - "--entry-point"
          - "monthlyTasks"
          - "--region"
          - "europe-west1"
          - "--runtime"
          - "nodejs20"
          - "--memory"
          - "256MB"
          - "--timeout"
          - "540s"
          - "--source"
          - "."

    - name: "gcr.io/cloud-builders/gcloud"
      args:
          - "functions"
          - "deploy"
          - "weekend-maintenance"
          - "--trigger-topic"
          - "weekend-maintenance"
          - "--entry-point"
          - "weekendMaintenance"
          - "--region"
          - "europe-west1"
          - "--runtime"
          - "nodejs20"
          - "--memory"
          - "256MB"
          - "--timeout"
          - "540s"
          - "--source"
          - "."

    - name: "gcr.io/cloud-builders/gcloud"
      args:
          - "functions"
          - "deploy"
          - "weekly-tasks"
          - "--trigger-topic"
          - "weekly-tasks"
          - "--entry-point"
          - "weeklyTasks"
          - "--region"
          - "europe-west1"
          - "--runtime"
          - "nodejs20"
          - "--memory"
          - "256MB"
          - "--timeout"
          - "540s"
          - "--source"
          - "."
